name: gatk_align
description: Perform alignment of fastqs/ubams
keywords:
  - bwamem2
  - gatk_mergebamalignment
  - picard_sortsam
  - samtools_fastq
  - samtools_index
  - alignment
  - fastq
  - ubam
modules:
  - bwamem2
  - gatk/mergebamalignment
  - picard/sortsam
  - samtools/fastq
  - samtools/index
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ entry_id:'test', sample_id:'test', single_end:false, rgID:"testp", rgLB:"lib1", PL:"ILLUMINA", rgPU:"unit1", rgSM:"test", read_group:'"@RG\\tID:testp\\tLB:lib1\\tPL:ILLUMINA\\PU:unit1\\tSM:test"' ]
  - input:
      type: file
      description: |
          List of input FastQ files of size 1 and 2 for single-end and paired-end data,
          respectively. Can also use ubams.
  - intervals:
      type: file
      description: Bed file with the genomic regions to be used for the sample, if any, not to be mixed up with file used for interval splitting.
  - fasta:
      type: file
      description: The reference fasta file
      pattern: "*.fasta"
  - fai:
      type: file
      description: Index of reference fasta file
      pattern: "*.fasta.fai"
  - dict:
      type: file
      description: GATK sequence dictionary
      pattern: "*.dict"
  - bwaindex:
      type: file
      description: BWAmem2 genome index files.
      pattern: "Directory containing BWA index *.{0132,amb,ann,bwt.2bit.64,pac}"
  - is_ubam:
      type: boolean
      description: |
          option to set whether input is an unaligned bam (true) or fastq (false),
          if true, it runs fastq conversion of the ubam file
      pattern: "{true,false}"
  - sort_order:
      type: value
      description: Picard sort order type for sorting prior to samtools indexing.
      pattern: "unsorted|queryname|coordinate|duplicate|unknown"

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
  - fastq_out:
      type: file
      description: compressed FASTQ files generated if input file was a ubam
      pattern: "[*_1.fastq.gz , *_2.fastq.gz]"
  - bwa_mem_out:
      type: file
      description: Output BAM file containing read alignments
      pattern: '*.{mapped.bam}'
  - sortsam_out:
      type: file
      description: Sorted mapped BAM file containing read alignments
      pattern: '*.{sorted.bam}'
  - sortsam_unmapped_out:
      type: file
      description: Sorted unmapped BAM file containing read alignments
      pattern: '*.{unmapped.sorted.bam}'
  - merge_bam_out:
      type: file
      description: The merged bam file
      pattern: "*.{merged.bam}"
  - samtools_index_out:
      type: file
      description: index file of the sorted and duplicate marked bam file.
      pattern: "*.{bai}"
  - intervals_out:
      type: file
      description: if samples were input along with an intervals file, it will be passed out here.

authors:
  - '@GCJMackenzie'
