name: samtools_chunking
description: Splits bam files into chunks using joint intervals file containing genomic intervals.
  - Samtools_view
  - Picard_addorreplacereadgroups
  - intervals_splitting
modules:
  - samtools/view
  - picard/addorreplacereadgroups
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ entry_id:'test', sample_id:'test', single_end:false, rgID:"testp", rgLB:"lib1", PL:"ILLUMINA", rgPU:"unit1", rgSM:"test", read_group:'"@RG\\tID:testp\\tLB:lib1\\tPL:ILLUMINA\\PU:unit1\\tSM:test"' ]
  - input:
      type: file
      description: List of input bam files to be split into chunks.
  - intervals:
      type: file
      description: Bed file containing the genomic regions to be used to split the input files into chunks.

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
  - ch_index_out:
      type: file
      description: index file of the chunked, redgroups added, bam file.
      pattern: "*.{bai}"
  - ch_bam_out:
      type: file
      description: Chunked bam files from samtools view.
      pattern: "*.{viewed.bam}"
  - ch_rg_bam_out:
      type: file
      description: Bam files chunked and new readgroups added.
      pattern: "*.{new_rg.bam}"
  - ch_interval_out:
      type: val
      description: String value containing the interval used to generate the related chunked bam file.
  - ch_format_out:
      type: list
      description: Outputs grouped into correct format to continue Atholl workflow.
      pattern: [meta, chunked bam file, bam file index, interval value]
authors:
  - '@GCJMackenzie'
