name: gatk_preprocess
description: Perform variant calling on a set of normal samples using mutect2 panel of normals mode. Group them into a genomicsdbworkspace using genomicsdbimport, then use this to create a panel of normals using createsomaticpanelofnormals.
keywords:
  - gatk4
  - applybqsr
  - baserecalibrator
  - picard_markduplictaes
  - picard_sortsam
  - samtools_index
  - BQSR
modules:
  - gatk4/applybqsr
  - gatk4/baserecalibrator
  - picard/sortsam
  - picard/markduplicates
  - samtools/index
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false, read_group:'"@RG\\tID:Seq01p\\tSM:Seq01\\tPL:ILLUMINA"' ]
  - input:
      type: file
      description: |
          List of bam files and their indexes to be pre-processed
  - intervals:
      type: val
      description: Interval used to create the chunk stored in the bam file.
  - fasta:
      type: file
      description: The reference fasta file
      pattern: "*.fasta"
  - fai:
      type: file
      description: Index of reference fasta file
      pattern: "*.fasta.fai"
  - dict:
      type: file
      description: GATK sequence dictionary
      pattern: "*.dict"
  - sort_order:
      type: value
      description: Picard sort order type for sorting prior to samtools indexing.
      pattern: "unsorted|queryname|coordinate|duplicate|unknown"
  - knownsites:
      type: file
      description: VCF file containing known sites (optional)
  - knownsites_tbi:
      type: file
      description: VCF index of dbsnp (optional)

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
  - markdup_out:
      type: file
      description: BAM file containing read alignments with duplicates marked
      pattern: '*.{markduplicates.bam}'
  - metrics_out:
      type: file
      description: Duplicate metrics file generated by picard
      pattern: "*.{metrics.txt}"
  - sortsam_dupesmarked_out:
      type: file
      description: sorted BAM file containing read alignments with duplicates marked
      pattern: '*.{sorted.bam}'
  - samtools_index_out:
      type: file
      description: index file of the sorted and duplicate marked bam file.
      pattern: "*.{bai}"
  - baserecalibrator_out:
      type: file
      description: Recalibration table from BaseRecalibrator
      pattern: "*.{table}"
  - applybqsr_out:
      type: file
      description: Recalibrated BAM file
      pattern: "*.{recalibrated.bam}"
  - applybqsr_index_out:
      type: file
      description: Recalibrated BAM file index
      pattern: "*.{recalibrated.bam.bai}"
  - ch_intervals_out:
      type: val
      description: Interval used to create the chunk stored in the bam file.
authors:
  - '@GCJMackenzie'
