name: gatk_haplotypecalling
description: |
  Run GATK haplotypecaller in GVCF mode
keywords:
  - gatk4
  - picard
  - haplotypecaller
  - renamesamppleinvcf
  - indexfeaturefile
modules:
  - gatk4/haplotypecaller
  - gatk4/indexfeaturefile
  - picard/renamesampleinvcf
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - input:
      type: list
      description: |
        list containing BAM files and their indexes to be run through haplotypecaller, also able to take CRAM as an input.
        OR if run_haplotc is false then it will contain gvcf files and their tbi indexes.
        e.g."[ [ id:'test' ], .{bam/cram}, {bam.bai/cram.crai} ]"
        OR "[[ id:'test' ], .g.vcf, .g.vcf.tbi]"
  - fasta:
      type: file
      description: The reference fasta file
      pattern: "*.fasta"
  - fai:
      type: file
      description: Index of reference fasta file
      pattern: "*.fasta.fai"
  - dict:
      type: file
      description: GATK sequence dictionary
      pattern: "*.dict"
  - sites:
      type: file
      description: Population vcf of germline sequencing, containing known sites.
      pattern: "*.vcf.gz"
  - sites_index:
      type: file
      description: Index file for the known sites.
      pattern: "*.vcf.gz.tbi"

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
  - haplotc_vcf:
      type: file
      description: Compressed gvcf file from haplotypecaller.
      pattern: "[ *g.vcf.gz ]"
  - haplotc_index:
      type: file
      description: Indexes of the haplotypecaller_gvcf file
      pattern: "[ *g.vcf.gz.tbi ]"
  - renamed_vcf:
      type: file
      description: Compressed gvcf file from haplotypecaller.
      pattern: "[ *renamed.g.vcf.gz ]"
  - renamed_index:
      type: file
      description: Indexes of the haplotypecaller_gvcf file
      pattern: "[ *g.vcf.gz.tbi ]"
  - haplotc_interval_out:
      type: val
      description: Interval value for the chunked vcf.
authors:
  - '@GCJMackenzie'
