name: gatk_mutect2_calling
description: Run GATK mutect2.
keywords:
  - gatk4
  - mutect2
  - variant_calling
modules:
  - gatk4/mutect2
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - input:
      type: list
      description: list of BAM files, also able to take CRAM as an input
      pattern: "[ *.{bam/cram} ]"
  - input_index:
      type: list
      description: list of BAM file indexes, also able to take CRAM indexes as an input
      pattern: "[ *.{bam.bai/cram.crai} ]"
  - tumor_normal:
      type: boolean
      description: Whether to run mutect2 in tumor normal mode
      pattern: true/false
  - tumor_only:
      type: boolean
      description: Whether to run mutect2 in tumor only mode
      pattern: true/false
  - create_sompon:
      type: boolean
      description: Whether to run mutect2 in panel of normals mode
      pattern: true/false
  - fasta:
      type: file
      description: The reference fasta file
      pattern: "*.fasta"
  - fai:
      type: file
      description: Index of reference fasta file
      pattern: "*.fasta.fai"
  - dict:
      type: file
      description: GATK sequence dictionary
      pattern: "*.dict"
  - germline_resource:
      type: file
      description: Panel of normal as compressed vcf file
      pattern: "*.vcf.gz"
  - germline_resource_tbi:
      type: file
      description: Index of pon_vcf file
      pattern: "*vcf.gz.tbi"
  - panel_of_normals:
      type: file
      description: Panel of normal as compressed vcf file
      pattern: "*.vcf.gz"
  - panel_of_normals_tbi:
      type: file
      description: Index of pon_vcf file
      pattern: "*vcf.gz.tbi"
output:
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
  - mutect2_vcf:
      type: list
      description: List of compressed vcf files to be used to make the gendb workspace
      pattern: "[ *.vcf.gz ]"
  - mutect2_tbi:
      type: list
      description: List of indexes of mutect2_vcf files
      pattern: "[ *vcf.gz.tbi ]"
  - mutect2_stats:
      type: list
      description: List of stats files that pair with mutect2_vcf files
      pattern: "[ *vcf.gz.stats ]"
  - mutect2_intervals:
      type: val
      description: List of intervals linked to the mutect2_vcf files
      pattern: "[ *vcf.gz.tbi ]"
  - mutect2_f1r2:
      type: list
      description: List of f1r2 files that pair with mutect2_vcf files
      pattern: "[ *vcf.gz.stats ]"

authors:
  - '@GCJMackenzie'
